require('aerial').setup({
  layout = {
    width = 50,
    default_direction = "prefer_left",
  },
  icons = {
    Text = "",
    Method = "m",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  highlight_closest = true,
  highlight_on_hover = true,
  autojump = true,
  close_on_select = true,
  show_guides = true,
})
